// Hedef bölüm alanı için yaygın bölüm isimleri — otomatik tamamlama listesi.
export const DEPARTMENTS: string[] = [
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hukuk",
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Endüstri Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Mimarlık",
  "Endüstriyel Tasarım",
  "Psikoloji",
  "İşletme",
  "İktisat",
  "Uluslararası İlişkiler",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Öğretmenlik (Sınıf/Branş)",
  "Mütercim Tercümanlık",
  "Biyomedikal Mühendisliği",
  "Havacılık ve Uzay Mühendisliği",
  "Moleküler Biyoloji ve Genetik",
  "Veteriner Hekimliği",
  "Fizyoterapi ve Rehabilitasyon",
  "Hemşirelik",
];
