// Piyasada yaygın bilinen YKS deneme/yayın markaları — yayınevi alanı için
// otomatik tamamlama listesi. Sıralama herhangi bir öneri/derece belirtmez.
export const PUBLISHERS: string[] = [
  "3D Yayınları",
  "Apotemi Yayınları",
  "Bilgi Sarmal Yayınları",
  "Bilfen Yayınları",
  "Çap Yayınları",
  "Endemik Yayınları",
  "Esen Yayınları",
  "FDD Yayınları",
  "Hız Yayınları",
  "Karekök Yayınları",
  "Limit Yayınları",
  "Nitelik Yayınları",
  "Özdebir Yayınları",
  "Palme Yayınları",
  "Sonuç Yayınları",
  "Tonguç Akademi",
  "Acil Yayınları",
  "Birey Eğitim Yayınları",
  "Croco Yayınları",
  "Ekol Yayınları",
  "Kafa Dengi Yayınları",
  "Kültür Fen Yayınları",
  "Marka Yayınları",
  "Master Yayınları",
  "Metin Yayınları",
  "Şahin Yayınları",
  "Yeni Nesil Yayınları",
];
